-- AlterTable
ALTER TABLE `TimeEntry` ADD COLUMN `friTimeOff` DOUBLE NOT NULL DEFAULT 0,
    ADD COLUMN `monTimeOff` DOUBLE NOT NULL DEFAULT 0,
    ADD COLUMN `satTimeOff` DOUBLE NOT NULL DEFAULT 0,
    ADD COLUMN `sunTimeOff` DOUBLE NOT NULL DEFAULT 0,
    ADD COLUMN `thuTimeOff` DOUBLE NOT NULL DEFAULT 0,
    ADD COLUMN `tueTimeOff` DOUBLE NOT NULL DEFAULT 0,
    ADD COLUMN `wedTimeOff` DOUBLE NOT NULL DEFAULT 0;
